name: CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo & checkout code
      uses: actions/checkout@v5

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm

    - name: Install NPM packages
      run: npm ci

    - name: Build project
      run: npm run build
    
    - name: Setup Pages
      uses: actions/configure-pages@v4

      # Upload build output as pages artifact
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist' # Set as build output folder

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4