# Create a workflow that calculates the hypotenuse of a right triangle given 2 sides:
# - Runs when manually triggered
# - Inputs are the lengths of the 2 sides
# - Print the hypotenuse value in the logs
# - Design this using 2+ jobs where you are moving data between jobs using outputs and needs

name: Calculate the Hypothenuse

on:
  workflow_dispatch:
    inputs:
      side_1:
        description: "Length of first side"
        type: number
      side_2:
        description: "Length of second side"
        type: number

jobs:
  name: "Job 1: Calculate hypothenuse"
  runs-on: ubuntu-latest
  outputs:
    hypothenuse: ${{ steps.hypothenuse.outputs.hypothenuse }}
  steps:
    - name: Calculate hypothenuse
      id: hypothenuse
      run: |
        HYPOTHENUSE=$(( (${{ inputs.side_1 }} ** 2 + ${{ inputs.side_2 }} ** 2) ** 0.5  ))
        echo "hypothenuse=$HYPOTHENUSE" >> $HYPOTHENUSE
        echo "Hypothenuse: $HYPOTHENUSE"